"""
Django settings for SmartPet project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

#Cargar variables de entorno
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "default-insecure-key")

DEBUG = os.getenv("DEBUG", "0") == "1"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".ngrok-free.dev",
    "*",   # permite acceso dentro de Docker
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.dev",
    "http://localhost",
    "http://127.0.0.1",
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'crispy_bootstrap5',
    'crispy_forms',
    'usuarios.apps.UsuariosConfig',

]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SmartPet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SmartPet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

MERCADOPAGO_ACCESS_TOKEN = "APP_USR-4109514335792921-102303-1d58fa2e0cbce684abbfbcce1f04b712-2942643233"
MERCADOPAGO_PUBLIC_KEY = "APP_USR-c1440066-9f7b-419b-a9fc-9e0d7261d790"

#ChileXpress API (FALTA IMPLEMENTAR LA API DE COTIZACIÓN DE ENVÍOS)

CHILEXPRESS_API_URL = "http://testservices.wschilexpress.com"
# Clave para calcular precios (Cotizador)
CHILEXPRESS_COTIZADOR_KEY = "62767e8bab944d17b4699ce9777ac83f"
# Clave para descargar lista de comunas (Coberturas)
CHILEXPRESS_COBERTURA_KEY = "4333f3611bfb4c2082786151cdf4b2e1"
# clave para ver estados de envíos (Seguimiento)
CHILEXPRESS_ENVIOS_KEY = "b92da5be550846d5a71e2acc2b06316a"

#API GMAIL
if DEBUG:
    # --- MODO DE DESARROLLO (DEBUG=True) ---
    # Imprime los emails en la terminal de 'runserver'
    # No necesitas una API key, es instantáneo y perfecto para probar.
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'smartpet-debug@localhost.com'
    
else:
    # --- MODO DE PRODUCCIÓN (DEBUG=False) ---
    # Esta es la configuración de Gmail que ya tenías (image_793ac8.png)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'smartpetweb1@gmail.com'
    EMAIL_HOST_PASSWORD = 'elqe idpe yxau pyee' # (Tu clave de app de Gmail)
    DEFAULT_FROM_EMAIL = '"SmartPet 🐾" <smartpetweb1@gmail.com>'

