# Generated by Django 5.2.6 on 2025-11-05 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 - Malo'), (2, '2 - Regular'), (3, '3 - Bueno'), (4, '4 - Muy Bueno'), (5, '5 - Excelente')], default=5)),
                ('comentario', models.TextField(blank=True, max_length=1000, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='usuarios.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('producto', 'usuario')},
            },
        ),
    ]
