# Generated by Django 5.2.6 on 2025-11-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_condicion_edad_categoria_slug_especie_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='condiciones',
            field=models.ManyToManyField(blank=True, related_name='productos', to='usuarios.condicion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='edades',
            field=models.ManyToManyField(blank=True, related_name='productos', to='usuarios.edad'),
        ),
        migrations.AddField(
            model_name='producto',
            name='razas',
            field=models.ManyToManyField(blank=True, related_name='productos', to='usuarios.raza', verbose_name='Razas Específicas'),
        ),
    ]
