# Generated by Django 5.2.6 on 2025-11-18 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_poblar_datos_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_envio',
            field=models.CharField(choices=[('ENVIO', 'Despacho a Domicilio'), ('RETIRO', 'Retiro en Tienda')], default='ENVIO', max_length=20, verbose_name='Tipo de Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.comuna'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.region'),
        ),
    ]
