# Generated by Django 5.2.6 on 2025-10-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_producto_stock_alter_producto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='creado_en',
            new_name='fecha_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='calle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comuna',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='depto_oficina',
            field=models.CharField(blank=True, help_text='Opcional', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='region',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='alto_cm',
            field=models.PositiveIntegerField(default=10, help_text='Alto del paquete en cm'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho_cm',
            field=models.PositiveIntegerField(default=10, help_text='Ancho del paquete en cm'),
        ),
        migrations.AddField(
            model_name='producto',
            name='largo_cm',
            field=models.PositiveIntegerField(default=10, help_text='Largo del paquete en cm'),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Peso del paquete en kg', max_digits=5),
        ),
    ]
