# Generated by Django 5.2.7 on 2025-10-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_creado_en_pedido_fecha_pedido_pedido_calle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('alimento', 'Alimento'), ('accesorio', 'Accesorio'), ('higiene', 'Higiene'), ('salud', 'Salud')], default='alimento', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='especie',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otros', 'Otros')], default='perro', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
