# Generated by Django 5.2.7 on 2025-10-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_producto_categoria_producto_especie_producto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('alimento', 'Alimento'), ('accesorio', 'Accesorio'), ('higiene', 'Higiene'), ('salud', 'Salud'), ('juguete', 'Juguete'), ('ropa', 'Ropa'), ('cama', 'Cama')], default='alimento', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='especie',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('pez', 'Pez'), ('ave', 'Ave'), ('roedor', 'Roedor'), ('reptil', 'Reptil'), ('otros', 'Otros')], default='perro', max_length=50),
        ),
    ]
