# Generated by Django 5.2.7 on 2025-10-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_producto_categoria_alter_producto_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('alimentos_secos', 'Alimentos Secos'), ('alimentos_humedos', 'Alimentos Húmedos'), ('antiparasitarios', 'Antiparasitarios'), ('camas', 'Camas y Escondites'), ('rascadores', 'Rascadores'), ('arenas', 'Arenas'), ('juguetes', 'Juguetes'), ('fuentes', 'Fuentes para Beber'), ('collares', 'Collares y Arnés'), ('placas', 'Placas Identificadoras'), ('higiene', 'Higiene'), ('repelentes', 'Limpieza y Repelentes'), ('calmantes', 'Productos Calmantes')], max_length=100, null=True),
        ),
    ]
