# Generated by Django 5.2.7 on 2025-10-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_producto_subcategoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='visible',
            field=models.BooleanField(default=True, help_text='Define si el producto es visible en el catálogo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='alto_cm',
            field=models.PositiveIntegerField(default=10, help_text='Altura del paquete en cm'),
        ),
    ]
