# Generated by Django 5.2.6 on 2025-11-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_producto_actualizado_en_producto_creado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='id_chilexpress',
            field=models.CharField(blank=True, help_text='El código de comuna (CGL) que usa Chilexpress', max_length=10, null=True),
        ),
    ]
