# Generated by Django 5.2.6 on 2025-11-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_comuna_id_chilexpress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='completado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('APROBADO', 'Pago Aprobado'), ('ENVIADO', 'Enviado'), ('ERROR_ENVIO', 'Error de Envío')], default='PENDIENTE', max_length=20, verbose_name='Estado del Pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='etiqueta_pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Etiqueta PDF'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Seguimiento'),
        ),
    ]
