# Generated by Django 5.2.6 on 2025-11-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_pedido_tipo_envio_alter_pedido_calle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_mercadopago',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Pago MP'),
        ),
    ]
