# Generated by Django 4.2.2 on 2025-11-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_pedido_id_mercadopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/', verbose_name='Foto de la mascota'),
        ),
    ]
